version: 2.1
jobs:
  test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: rustup component add
          command: rustup component add clippy rustfmt
      - run:
          name: fmt
          command: cargo fmt --all -- --check
      - run:
          name: clippy
          command: cargo clippy --all-targets --all-features -- -D warnings
      - run:
          name: build & test
          command: RUST_BACKTRACE=1 cargo test --verbose --all -- --nocapture

workflows:
  version: 2
  test:
    jobs:
      - test
